#--------------------------------------------------------------------------------
# Update Kubelet cAdvisor port for DD monitoring.
#--------------------------------------------------------------------------------
- name: "Update /etc/systemd/system/kubelet.service.d/10-kubeadm.conf for --cadvisor-port=4194 option."
  lineinfile:
    path: "{{ KUBELET_CONFIG_FILE }}"
    regexp: '^Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=.*'
    line: 'Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=4194"'
    state: "present"
    create: "yes"
