#--------------------------------------------------------------------------------
# Delete previous installation and clear application_home.
#--------------------------------------------------------------------------------

- name: "Stop port forwarding to the application pod"
  shell: |
    cd {{ application_home }}
    for f in $( ls *.pid ) ; do kill $( cat ${f} && rm ${f} ) ; done
  with_items: "{{ pods }}"
  ignore_errors: true

- name: "Check {{ application }} has been installed"
  shell: |
    kubectl get pod { item.name }} -n {{ item.namespace }}
  register: isAppInstalled
  ignore_errors: true
  with_items: "{{ pods }}"

- debug:
    msg: "{{ isAppInstalled }}"

- name: "Delete {{ application }} application"
  shell: |
    cd {{ application_home }}
    kubectl delete -f {{ item.manifest }}
  ignore_errors: true
  with_items: "{{ pods }}"

- name: "Wait {{ application }} application terminated"
  shell: |
    cd {{ application_home }}
    while [ "$(kubectl get pod -n {{ item.namespace }} --no-headers | grep {{ item.name }} | awk '{ print $3 }')" == "Terminating" ]
      do kubectl get pod -n {{ item.namespace }}
      sleep 3
    done
  ignore_errors: true
  with_items: "{{ pods }}"

- name: "Check kuard terminated for sure"
  shell: |
    kubectl get pods --all-namespaces
  ignore_errors: true

- pause:
    minutes: 1

- name: "Clear {{ application_home }}"
  file:
    path:     "{{ application_home }}"
    state:    "absent"

#--------------------------------------------------------------------------------
# Provision application artefacts
#--------------------------------------------------------------------------------
- name: "Create {{ application_home }}"
  file:
    path:     "{{ application_home }}"
    state:    "directory"
    group:    "{{ K8S_GROUP }}"
    mode:     "0750"

- name: "Git clone {{ application }} application"
  shell: |
    git clone {{ application_git_url }} {{ application_home }}

- name: "Copy {{ application }}"
  copy:
    src: "{{ role_path }}/files/{{ application_manifest }}"
    dest: "{{ application_home }}/{{ application_manifest }}"
    owner: "{{ K8S_ADMIN }}"
    mode: 0644
  when: copy_application_manifest

#--------------------------------------------------------------------------------
# Deploy application
#--------------------------------------------------------------------------------
- name: "Deploy {{ application }} application"
  shell: |
    cd {{ application_home }}
    kubectl apply -f {{ item.manifest }}
  with_items: "{{ pods }}"

- name: "Wait for {{ application }} ready"
  shell: |
    cd {{ application_home }}
    while [ "$(kubectl get pod -n {{ item.namespace }} --no-headers | grep {{ item.name }} | awk '{ print $3 }')" != "Running" ]
      do kubectl get pod -n {{ item.namespace }} | tee -a {{ item.name }}.log
      sleep 1
    done
  with_items: "{{ pods }}"

- name: "Port forward from {{ item.node_port }} of the host to {{ item.pod_port }} in pod"
  shell: |
    cd {{ application_home }}
    nohup kubectl port-forward {{ item.name }} {{ item.node_port }}:{{ item.pod_port }} &
    echo $! > {{ item.name }}.pid
  with_items: "{{ pods }}"

# To access kuard:
# ssh -i ~/.ssh/aws_maonishi_us-west-1pem.pem -L localhost:8080:127.0.0.1:8080 centos@50.18.71.232
# http://localhost:8080