#--------------------------------------------------------------------------------
# Update Kubelet cAdvisor port for DD monitoring.
#--------------------------------------------------------------------------------
#- name: "Update {{ KUBELET_CONFIG_FILE }} for --cadvisor-port=4194 option."
#  lineinfile:
#    path: "{{ KUBELET_CONFIG_FILE }}"
#    regexp: '^Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=.*'
#    line: 'Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=4194"'
#    state: "present"
#    create: "yes"

- name: "Update {{ KUBELET_CONFIG_FILE }} to set cAdvisor port."
  replace:
    path:     "{{ KUBELET_CONFIG_FILE }}"
    regexp:   '^Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=(.+)"\s*$'
    replace:   'Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port={{ CADVISOR_PORT }}"'
    backup:   "yes"

- name: "Force systemd to reread configs (2.4 and above)"
  systemd: daemon_reload=yes

- name: "Restart k8s services"
  service:
    name:     "{{ item }}"
    state:    "restarted"
    enabled:  "yes"
  with_items: "{{ K8S_COMMON_SERVICES }}"

#--------------------------------------------------------------------------------
# Datadog K8S on host
#--------------------------------------------------------------------------------
- include: "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"
- name: "Adding dd-agent user to docker group."
  user:
    name:   "{{ item }}"
    groups: "{{ docker_group }}"
    append: "yes"                 # useradd -aG
  with_items:
    - "dd-agent"

- name: "Datadog Process and Container Monitoring (https://docs.datadoghq.com/infrastructure/process/)"
  lineinfile:
    path: /etc/dd-agent/datadog.conf
    regexp: '^process_agent_enabled:(\s)+true(\s)*'
    insertafter: '^[Main].*$'
    line: 'process_agent_enabled: true'

#--------------------------------------------------------------------------------
# https://docs.datadoghq.com/integrations/kubernetes_state/ is incorrect.
# No need to use /etc/dd-agent/conf.d/kubernetes_state.yaml.
#--------------------------------------------------------------------------------
#- name: "Place kubernetes_state manifest."
#  template:
#    src: "{{ role_path }}/templates/kubernetes_state.yaml.j2"
#    dest: "/etc/dd-agent/conf.d/kubernetes_state.yaml"
#    owner: "dd-agent"
#    group: "dd-agent"
#    mode: 0640
#--------------------------------------------------------------------------------


#--------------------------------------------------------------------------------
# Resgart DD agent on host
#--------------------------------------------------------------------------------
- name: "Restart dd-agetnt on the host"
  shell: |
    /etc/init.d/datadog-agent restart
  register: ddagent_restart