#--------------------------------------------------------------------------------
# Make sure dd-agent user can access K8S client certificates for K8S checks.
# This has been done in K8S installation module but to be sure.
#--------------------------------------------------------------------------------
- name: "Give rx access to {{ K8S_CA_HOME }} for {{ K8S_GROUP }}"
  file:
    path:     "{{ K8S_CA_HOME }}"
    state:    "directory"
    group:    "{{ K8S_GROUP }}"
    mode:     0750

- name: "Change directory permission for {{ K8S_GROUP }} to reach {{ K8S_CA_HOME }}"
  shell: |
    dir="{{ K8S_CA_HOME }}"
    while [[ ${dir} != "/etc" && -d ${dir} ]]; do chgrp {{ K8S_GROUP }} "${dir}" && chmod g+x "${dir}" && dir=$(dirname "${dir}"); done;
  args:
    executable: /bin/bash

- name: "Give r access to client certificate files for {{ K8S_GROUP }}"
  file:
    path:     "{{ item }}"
    state:    "file"
    group:    "{{ K8S_GROUP }}"
    mode:     0640
  with_items:
    - "{{ APISERVER_CLIENT_CRT }}"
    - "{{ APISERVER_CLIENT_KEY }}"
    - "{{ APISERVER_CA_CRT }}"
