#--------------------------------------------------------------------------------
# Clean up previous intallation.
#--------------------------------------------------------------------------------
- name: "Delete secrets for api server client certifiate and key"
  become: true
  become_user: "{{ K8S_ADMIN }}"
  shell: |
    kubectl get secret k8s-certs -n {{ DATADOG_NAMESPACE }} && kubectl delete secret k8s-certs -n {{ DATADOG_NAMESPACE }}
    sleep 3
  ignore_errors: true
  run_once: true

#--------------------------------------------------------------------------------
# Create secrets for client certificates for dd-agent to use.
#--------------------------------------------------------------------------------
- name: "Create secrets for api server client certifiate and key"
  shell: >
    KUBECONFIG={{ KUBECONFIG_ADMIN }}
    kubectl create secret generic k8s-certs
    --namespace={{ DATADOG_NAMESPACE }}
    --from-file={{ APISERVER_CLIENT_CRT }}
    --from-file={{ APISERVER_CLIENT_KEY }}
    --from-file={{ APISERVER_CA_CRT }}
#    --from-file={{ KUBELET_CLIENT_CRT }}
#    --from-file={{ KUBELET_CLIENT_KEY }}
#    --from-file={{ KUBELET_CA_CRT }}
#    --from-literal=token={{ DATADOG_K8S_TOKEN }}
  run_once: true
