---
- name: "K8s installation for master"
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - kube_state_metrics
    - datadog_installation
    - datadog_k8sintegration_common
    - datadog_k8sintegration_master
    - datadog_check_k8s
#    - fluentd_elasticsearch