- name: Get list of instances to stop...
  ec2_remote_facts:
    filters:
      instance-state-name: running
    region:          "{{ aws_region }}"
    # Use environment variables
    #aws_access_key:       "{{ ec2_access_key }}"
    #aws_secret_key:       "{{ ec2_secret_key }}"
  register: ec2_instances
