#--------------------------------------------------------------------------------
# Install Helm
# https://docs.bitnami.com/kubernetes/get-started-kubernetes/#k8_tutorial_step4
#--------------------------------------------------------------------------------
- name: Download helm
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get
    dest: "~{{ K8S_ADMIN }}/helm_install.sh"
    force_basic_auth: yes

- name: "Set exec permission"
  file:
    path:     "~{{ K8S_ADMIN }}/helm_install.sh"
    owner:    "{{ K8S_ADMIN }}"
    group:    "{{ K8S_GROUP }}"
    state:    "file"
    mode:     0740

- name: "Install helm"
  shell: "{{ item }}"
  args:
    chdir: "~{{ K8S_ADMIN }}"
  with_items:
    - PATH=${PATH}:/usr/local/bin ./helm_install.sh
    - PATH=${PATH}:/usr/local/bin  /usr/local/bin/helm init --upgrade

- name: "Install helm"
  shell: |
    kubectl --namespace kube-system get pods | grep tiller

