#--------------------------------------------------------------------------------
# DD Agent
#--------------------------------------------------------------------------------
- name: "Install/update Datadog agent"
  shell: |
    DD_API_KEY={{ DATADOG_API_KEY }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"