- include_vars:   "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"
- include_tasks : "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"

- name: Install ntp packages...
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages}}"

- name: Start the ntp and haveged services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - "{{ pkg_ntp }}"
    - "{{ pkg_haveged }}"