#K8S_GROUP:
K8S_ADMIN : maonishi
K8S_GROUP: k8s

#--------------------------------------------------------------------------------
# [Security]
#--------------------------------------------------------------------------------
DECRYPT_KEY_FILE: "~/.ssh/private.pem"
