SYS_USER: maonishi
PKG_USER: maonishi


#K8S_GROUP:
K8S_ADMIN : maonishi
K8S_GROUP: k8s

#--------------------------------------------------------------------------------
# Constants
#--------------------------------------------------------------------------------
NODE_TYPE_MASTER: "master"
NODE_TYPE_WORKER: "worker"
CNI_PROVIDER_FLANNEL: "flannel"

#--------------------------------------------------------------------------------
# [Security]
#--------------------------------------------------------------------------------
DECRYPT_KEY_FILE: "~/.ssh/private.pem"

#--------------------------------------------------------------------------------
# Docker
#--------------------------------------------------------------------------------
docker_group: "docker"

#--------------------------------------------------------------------------------
# Etcd
#--------------------------------------------------------------------------------
ETCD_CONFIG_HOME: /etc/kubernetes

#--------------------------------------------------------------------------------
# K8S
#--------------------------------------------------------------------------------
K8S_CONFIG_HOME: "/etc/kubernetes"
K8S_CONFIG_FILE: "{{ K8S_CONFIG_HOME}}/config"
KUBELET_CONFIG_FILE: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

K8S_PACKAGES_PREREQUISITES:
  - kubernetes-cni-0.6.0-0.x86_64

K8S_PACKAGES_PREREQUISITES_REMOVE:
  - kubernetes-cni


K8S_PACKAGES:
#  - kubeadm
#  - kubelet
#  - kubectl
  - kubeadm-1.8.6-0.x86_64
  - kubectl-1.8.6-0.x86_64
  - kubelet-1.8.6-0.x86_64
  - flannel
  - docker

K8S_PACKAGES_REMOVE:
  - kubeadm
  - kubelet
  - kubectl
  - kubernetes-cni
  - flannel
  - docker


K8S_COMMON_SERVICES:
# Start flannel is via kubectl apply -f flanne.yaml
  - kubelet

# Note that Docker requires CNI (e.g. Flannel) as pre-requisite service for K8S.
# See /etc/systemd/system/docker.service.requires/flanneld.service
K8S_NETWORK_PROVIDER: "{{ CNI_PROVIDER_FLANNEL }}"
K8S_NETWORK_SERVICES:
  - flanneld

KUBEPROXY_PORT: 8001