#--------------------------------------------------------------------------------
# K8S REST API response checks.
#--------------------------------------------------------------------------------
- name: "Delete kubestate metrics if exists"
  become: true
  become_user: "{{ K8S_ADMIN }}"
  shell: |
    kubectl delete -f {{ role_path|basename }}
  args:
    chdir: "{{ DATADOG_MANIFEST_HOME }}"
  ignore_errors: true
  run_once: true

- name: "Place kubestate metrics manifests for K8S services"
  copy:
    src: "{{ role_path }}/files/manifests/"
    dest: "{{ DATADOG_MANIFEST_HOME }}/{{ role_path|basename }}"
    owner: "dd-agent"
    group: "dd-agent"
    mode: 0770
  run_once: true

- name: "Deploy kubestate metrics"
  become: true
  become_user: "{{ K8S_ADMIN }}"
  shell: |
    kubectl apply -f {{ role_path|basename }}
  args:
    chdir: "{{ DATADOG_MANIFEST_HOME }}"
  run_once: true

# https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-access-to-the-privileged-scc
# https://access.redhat.com/solutions/3120011
- name: "Add required previlleage to use hostPath and access API resources"
  become: true
  become_user: "{{ K8S_ADMIN }}"
  shell: |
    oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:{{ KUBESTATE_NAMESPACE }}:{{ KUBESTATE_SERVICE_ACCOUNT }}
  when: DISTRIBUTION == DISTRIBUTION_OSE