#--------------------------------------------------------------------------------
# Datadog agent setups
#--------------------------------------------------------------------------------
- name: "Place dd-agent daemonset manifest."
  template:
    src: "{{ role_path }}/templates/dd-agent.yaml.j2"
    dest: "~{{ K8S_ADMIN }}/dd-agent.yaml"
    owner: "{{ K8S_ADMIN }}"
    mode: 0644

- name: "Check if dd-agent has been installed."
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl get daemonset dd-agent
  register: isDDAgentRunning
  ignore_errors: "true"

- name: "Delete and redeploy dd-agent if already installed."
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f ~{{ K8S_ADMIN }}/dd-agent.yaml
    kubectl delete daemonset dd-agent
  when: isDDAgentRunning.rc == 0

- name: "Deploy dd-agent if not already installed."
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl create -f ~{{ K8S_ADMIN }}/dd-agent.yaml
  when: isDDAgentRunning.rc != 0
