- name: "EPEL repository key"
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: "Install EPEL package"
  yum:
    name: "epel-release"
    state: "latest"
    update_cache: "true"
