endpoints:
  apiserver:
    protocol:       "{{ APISERVER_PROTOCOL }}"
    host:           "{{ ansible_fqdn }}"
    port:           "{{ APISERVER_PORT }}"
    path:           "{{ APISERVER_HELATH_ENDPOINT }}"
    http_code:      200
    content_match:  "^ok$"
    ca_certs:       "{{ APISERVER_CA_CRT }}"
    client_cert:    "{{ APISERVER_CLIENT_CRT }}"
    client_key:     "{{ APISERVER_CLIENT_KEY }}"
  etcd:
    protocol:       "{{ ETCD_PROTOCOL }}"
    # ETCD (K8S 1.9) binds on localhost I/F only.
    host:           localhost
    port:           "{{ ETCD_PORT }}"
    path:           "{{ ETCD_HELATH_ENDPOINT }}"
    http_code:      200
    content_match:  '^\{"health": "true"\}$'
    ca_certs:       "{{ ETCD_CA_CRT }}"
    client_cert:    "{{ ETCD_CLIENT_CRT }}"
    client_key:     "{{ ETCD_CLIENT_KEY }}"
  kubelet:
    protocol:       "{{ KUBELET_PROTOCOL }}"
    host:           "{{ ansible_fqdn }}"
    port:           "{{ KUBELET_PORT }}"
    path:           "{{ KUBELET_HEALTH_ENDPOINT }}"
    http_code:      200
    content_match:  '^ok$'
    ca_certs:       "{{ KUBELET_CA_CRT }}"
    client_cert:    "{{ KUBELET_CLIENT_CRT }}"
    client_key:     "{{ KUBELET_CLIENT_KEY }}"
