#--------------------------------------------------------------------------------
# Make sure dd-agent user can access K8S client certificates for K8S checks.
# This has been done in K8S installation module but to be sure.
#--------------------------------------------------------------------------------
- name: "Give rx access to {{ K8S_CA_HOME }} for {{ K8S_GROUP }}"
  file:
    path:     "{{ K8S_CA_HOME }}"
    state:    "directory"
    group:    "{{ K8S_GROUP }}"
    mode:     0750
    recurse:  yes

- name: "Give r access to client certificate files for {{ K8S_GROUP }}"
  file:
    path:     "{{ item }}"
    state:    "file"
    group:    "{{ K8S_GROUP }}"
    mode:     0640
  with_items:
    - "{{ APISERVER_CLIENT_CRT }}"
    - "{{ APISERVER_CLIENT_KEY }}"
    - "{{ APISERVER_CA_CRT }}"
    - "{{ KUBELET_CLIENT_CRT }}"
    - "{{ KUBELET_CLIENT_KEY }}"
    - "{{ KUBELET_CA_CRT }}"
    - "{{ ETCD_CLIENT_CRT }}"
    - "{{ ETCD_CLIENT_KEY }}"
    - "{{ ETCD_CA_CRT }}"

#--------------------------------------------------------------------------------
# K8S REST API response checks.
#--------------------------------------------------------------------------------
- name: "Place dd-agent http_check manifest for K8S services"
  template:
    src: "{{ role_path }}/templates/http_check_k8s.yaml"
    dest: "{{ DATADOG_AGENT_HOME }}/conf.d/http_check.yaml"
    owner: "dd-agent"
    group: "dd-agent"
    mode: 0640
  notify: "restart_datadog"
