---
- name: "K8s installation for master"
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - datadog_installation
    - datadog_k8sintegration_common
    - datadog_check_k8s

- name: K8s configurations for master
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: "{{ K8S_ADMIN }}"
  roles:
    - datadog_k8sintegration_master
