- name: K8s setup for master
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common
    - master
    - pki
    - user
    - helm

- name: "K8s add-on setup with "{{ K8S_ADMIN}}" user"
  hosts: masters
  any_errors_fatal: true
  become: yes
  become_user: "{{ K8S_ADMIN}}"
  become_method: sudo
  roles:
    - dashboard
