endpoints:
  etcd:
    protocol:       "{{ ETCD_PROTOCOL }}"
    # ETCD (K8S 1.9) binds on localhost I/F only.
    host:           localhost
    port:           "{{ ETCD_PORT }}"
    path:           "{{ ETCD_HELATH_ENDPOINT }}"
    http_code:      200
    content_match:  '^\{"health": "true"\}$'
    ca_certs:       "{{ ETCD_CA_CRT }}"
    client_cert:    "{{ ETCD_CLIENT_CRT }}"
    client_key:     "{{ ETCD_CLIENT_KEY }}"
