- name: Build start_hosts dictionary
  set_fact:
    start_hosts: "{{ start_hosts }} + [ '{{ item.id }}' ]"
  when: item.tags.autostart|default("false") == "true"
  with_items: "{{ ec2_instances.instances }}"

- name: List instnaces to start
  debug:
    msg: "--------------------------------------------------------------------------------"
  debug:
    msg: "{{ start_hosts }}"
  debug:
    msg: "--------------------------------------------------------------------------------"

- name: Start EC2 instances whose 'autostart' tag value is true
  ec2:
    instance_ids: "{{ start_hosts }}"
    region:       "{{ aws_region }}"
    state:        "running"
    wait:         "true"
    # Use environment variables
    #aws_access_key:       "{{ ec2_access_key }}"
    #aws_secret_key:       "{{ ec2_secret_key }}"
