---
- name: System setup for all servers.
  hosts: environment
  any_errors_fatal: true
  become: yes
  roles:
    - common
    - swapoff
    - selinux
    - firewalld
    - iptable
    - hosts
    - ntp
    - docker
