apiVersion: {{ RBAC_API_VERSION }}
kind: RoleBinding
metadata:
  name: kube-state-metrics
  namespace: {{ KUBESTATE_NAMESPACE }}
roleRef:
  apiGroup: v1
  kind: Role
  name: kube-state-metrics-resizer
subjects:
- kind: ServiceAccount
  name: {{ KUBESTATE_SERVICE_ACCOUNT }}
  namespace: {{ KUBESTATE_NAMESPACE }}

